ahsokannibal/nvs

- fonctions.php
premier test réalisé sur github
> premier commit test de jack

- bdd/nvs_data.sql
Ajout de l'auto increment sur les persos
> Ajout de l'auto inscrement à partir de 101 pour les persos

- bdd/nvs_data.sql
> ajout de la table  gestion les ordres du jour au niveau des compagnies

- index.php
- jeu/jouer.php
> Ajout du forum NVS3

- jeu/evenement.php
- jeu/jouer.php
- mvc/model/Building.php
- mvc/model/Camp.php
- mvc/model/Event.php
- mvc/model/Item.php
- mvc/model/Model.php
- mvc/model/Perso.php
- mvc/model/User.php
- mvc/model/Vehicle.php
Mise en place du MVC.
J'ai mis un exemple de modèle "Event" qui gère les requêtes liées aux évènements. Pour le moment je n'ai mis que l'action de récupérer tous les évènements d'un perso.
J'ai commenté son intégration sur la page "évènements" pour que vous ayez une idée.
Correctifs :
- Prise en compte du trébuchage et de la chance dans les évènements
- Correction de grammaire mineure
> MVC et correctifs

- jeu/action.php
- jeu/f_action.php
Le dépôt d'or au sol n'était pas codé (étrangement).
- Affichage de l'or dans la page déposer objet.
- Traitement du dépôt (enlever l'or du joueur et ajouter l'or sur la carte)
> Codage du dépôt d'or au sol

- jeu/agir.php
- jeu/f_combat.php
autorisation gain pc sur bataillon
pas de soins si cible peu blessee
diminution gain xp
> modif gain soigneur

- mvc/view/home.php
- mvc/view/layouts/app.php
- mvc/view/layouts/guest.php
- public/css/app.css
Quelques modifs à la suite des commentaires sur le problème d'affichage sur mobile.
> modification de l'affichage accueil

- bdd/nvs_tables.sql
Ajout dans le fichier sql table de la table "Camp".
> création de la table CAMP

- mvc/model/Building.php
- mvc/model/Camp.php
- mvc/model/Event.php
- mvc/model/Grade.php
- mvc/model/Item.php
- mvc/model/Perso.php
- mvc/model/User.php
- mvc/model/Vehicle.php
Ajouts de fonctions et modifications des modèles existants.
> modifs modèles

- inscription.php
- jeu/f_entete.php
Légères modifs de la page d'inscription pour remonter les erreurs dans la vue et modif des fonctions entêtes qui me remontaient une erreur "NULL" dans PHP.
Suppression des boutons évènements et cv pour un perso non trouvé (n'existe pas ou pendu).
> page inscription et fonction entêtes

- jeu/f_carte.php
- jeu/jouer.php
C'est fait mais quelle galère... Il y a du code qui copie une fonction qui elle même est intégrée, en plus du code...
Il y a de sacrées redondances
> Action de capturer accessible qu'aux Infs

- jeu/action_pnj.php
le classement dernier tombe n'Ãtait pas mis a jour, et il n'y avait pas de perte d xpi notamment...
> fix capture par pnj

- jeu/carte2.php
- mvc/model/Map.php
J'ai ajouté le brouillard de guerre. Aucun camp ne verra la carte s'il ne l'a pas découverte. J'ajoute le modèle "MAP" pour la refacto.
> Brouillard de guerre

- bdd/nvs_data.sql
- bdd/nvs_tables.sql
- jeu/sac.php
commandes sql a executer apres deploiement:
CREATE TABLE `objet_as_type_unite` (
`id_objet` int(11) NOT NULL,
`id_type_unite` int(11) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
INSERT INTO `objet_as_type_unite` (`id_objet`, `id_type_unite`) VALUES
(5, 3),
(5, 4),
(5, 5),
(6, 1),
(6, 2),
(6, 3),
(6, 4),
(6, 5),
(6, 7),
(7, 1),
(7, 2),
(7, 3),
(7, 4),
(7, 5),
(7, 7);
update perso set bonusPM_perso=bonusPM_perso-1 where id_perso IN (select id_perso from perso_as_objet where id_objet=5 and equip_objet=1) and (type_perso = 1 || type_perso = 2 || type_perso = 7);
update perso_as_objet set equip_objet=0 where id_objet=5 and equip_objet=1 and id_perso in (select id_perso from perso where type_perso = 1 || type_perso = 2 || type_perso = 7);
> bottes pas equipables par cavalerie

- jeu/admin_compagnies.php
- jeu/recrut_compagnie.php
- jeu/tresor_compagnie.php
Lors du deploiement:
DELETE FROM message_perso WHERE id_message=0;
> tentative reparation message non lus invisible

- jeu/admin_teleporte_bat.php
- jeu/agir.php
- jeu/f_carte.php
- jeu/f_combat.php
- jeu/jouer.php
Ajout bonus portée +1 sur colline +2 sur montagne
Ajout téléportation dans train depuis console admin
Correction bug attaque avec arme qui a une portée de base 4+ depuis un bâtiment
Amelioration fonction get_distance pour récuéprer la case la plus proche d'un batiment
> Portee high ground

- bdd/nvs_data.sql
deploiement:
update perso set paMax_perso=10 where type_perso=7;
> donne 10PA aux cavs legeres

- bdd/nvs_tables.sql
- jeu/bataillon.php
- jeu/classement.php
- jeu/f_recrutement.php
- jeu/gestion_grouillot.php
- jeu/gestion_inactif.php
- jeu/jouer.php
- jeu/recrutement.php
deploiement:
ALTER TABLE perso ADD est_renvoye tinyint(1) NOT NULL DEFAULT '0';
> renvoi perso

- jeu/recrutement.php
- regles/regles_unites.php
nombre par bataillon et grade mini
> suppression restrictions specifiques au chien

- index.php
- inscription.php
- jeu/jouer.php
- mvc/view/home.php
- public/css/app.css
Affichage pour expliquer que le jeu est en mode maintenance et qu'il rouvrira plus tard. Il faudra rendre possible le message de maintenance pour plus tard
> mode maintenance

- jeu/jouer.php
- login.php
J'ai rencontré des fonctions dépréciées en relançant NvS sur mon local car je suis passé sur PHP 8. J'ai donc fait les adaptations. Les modifs n'auront pas d'impact sur les versions antérieures.
> modifs de fonctions dépréciées

- jeu/jouer.php
> Changements liens discord

- regles/regles.php
- regles/regles_action_spe.php
- regles/regles_animation.php
- regles/regles_armees.php
- regles/regles_batiments.php
- regles/regles_caracs.php
- regles/regles_carte.php
- regles/regles_conduite.php
- regles/regles_header.php
- regles/regles_introduction.php
- regles/regles_modalites_victoire.php
- regles/regles_objets.php
- regles/regles_pnjs.php
- regles/regles_unites.php
Ajout d'un fichier header (qui contient la nav bar) appelé dans chaque fichier.
> maj regles MJ, mod victoire, creer compagnie, baisse precision pour armes à distance

- jeu/action.php
- jeu/anim_gestion_perso_pnj.php
- jeu/f_action.php
- jeu/f_combat.php
- jeu/jouer.php
- Les PNJ "personnage" ne donnent plus de PC lorsqu'ils sont attaqués ou soignés,
- corrections de quelques erreurs d'orthographe et grammaire
> suppression gain PC PNJ

- jeu/action_degradation_batiment.php
deploiement:
update cron jeu/action_degradation_batiment.php
> degration batiments

- jeu/evenement.php
- jeu/jouer.php
deploiement:
update evenement set phrase_evenement='a capture le batiment', nomCible_evenement='Plantation Calhoun' where IDCible_evenement=50002; update evenement set phrase_evenement='a capture le batiment', nomCible_evenement='Repere de la soif' where IDCible_evenement=50003; update evenement set phrase_evenement='a capture le batiment', nomCible_evenement='Refuge des planques' where IDCible_evenement=50004; update evenement set phrase_evenement='a capture le batiment', nomCible_evenement='Ranch du vieux Ned' where IDCible_evenement=50005; update evenement set phrase_evenement='a capture le batiment', nomCible_evenement='Ponton maudit' where IDCible_evenement=50006;
> fix evement capture batiment

- jeu/nouveau_message.php
note : les noms de persos devraient pas etre encodes comme ils le sont
> corrige envoi de mp a des persso ayant une quote dans le nom

- app/validator/formValidator.php
- creation_carte/utils_carte.php
- jeu/admin_map.php
- jeu/admin_nvs.php
- jeu/admin_teleporte_bat.php
- mvc/controller/controller.php
- mvc/controller/mapController.php
- mvc/model/Administration.php
- mvc/model/Building.php
- mvc/model/Map.php
- mvc/model/Perso.php
- mvc/view/admin/index.php
- mvc/view/layouts/app.php
- mvc/view/map/create.php
- mvc/view/map/index.php
- Passage en mvc partiel pour la gestion de carte
- Ajout de fonctionnalités admin pour la gestion des cartes (créer, éditer, supprimer)
- Ajout de fonctionnalité de téléportation de tous les persos vers un fort du camp
- Ajout d'un validateur de formulaire (évolutif)
- Modification d'une partie du design administration et gestion de cartes
> refacto Gestion de la carte

- bdd/nvs_tables.sql
- index.php
- jeu/admin_nvs.php
- mvc/Db/Db.php
- mvc/controller/mapController.php
- mvc/model/Administration.php
- mvc/model/Model.php
- mvc/view/admin/index.php
- mvc/view/home.php
- public/css/app.css
- Ajout de la fonctionnalité de paramétrage du message de maintenance affiché sur l'accueil du site.
- Modification mineure du nom de la fonctionnalité de vérification du mode maintenance
- Modification mineure du chemin de certains "require_once"
- Modification mineure de l'affichage du message de maintenance
Attention : Obligation d'ajouter dans la BDD la colonne "msg" dans la table "config_jeu"
> message de maintenance personnalisable

- jeu/admin_nvs.php
- jeu/admin_teleporte_bat.php
- Changement du nom de la fonction de récupération du mode maintenance
- Ajout de redirection pour l'ouverture/fermeture du mode maintenance
> changement nom de fonction

- jeu/batiment.php
- jeu/generer_plan_gare.php
- jeu/image_gare.php
- jeu/jouer.php
reprise du code de matthinator
> Reprisde correctif gare

- jeu/admin_nvs.php
- jeu/admin_teleporte_bat.php
- Changement du nom de la fonction de récupération du mode maintenance
- Ajout de redirection pour l'ouverture/fermeture du mode maintenance
> hotfix mode maintenance

- mvc/model/Model.php
- mvc/view/home.php
- mvc/view/map/create.php
- mvc/view/map/index.php
Optimisation des requêtes de la DAO
+ modifications mineures
> Optimisation de la DAO

- jeu/carte/Case.js
- jeu/carte/carte.js
- jeu/carte/functions_carte.php
pour accelerer l'affichage de la visue
> Optimisation visue

- jeu/action_train.php
- jeu/batiment.php
- jeu/generer_plan_gare.php
aucune image n'est enregistree sur le serveur, elle est cree et utilisee directement sans etre enregistree
> Proposed fix - Affichage des rails

- mvc/controller/itemController.php
- mvc/view/item/admin/create.php
- Résolution d'un problème de javascript pour l'affichage de la prévisualisation de l'image téléversée
- Ajout : renvois des données de formulaire sur les erreurs "inconnues"
> hotfix création objet

- jeu/agir.php
- jeu/f_combat.php
https://trello.com/c/qDoMfgir/40-protection-des-nouveaux
> feat: adjust PC

- jeu/jouer.php
- mvc/model/Model.php
- Forcer les tables à être en minuscule dans les modèles
- Misc : remise en état de certains liens dans la page jouer.php
> Gestion des objets - Modèles
